apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot_simulator
spec:
  replicas: 30
  selector:
    matchLabels:
      app: iot_simulator
  template:
    metadata:
      labels:
        app: iot_simulator
    spec:
      containers:
        - name: iot_simulator
          image: marcobevilacqua94/iot_simulator:latest
          command: ["java","-jar","iot_simulator.jar","-h","cb-example-persistent"]